### ISSUE TITLE
[GH Actions] Set up caching for npm installs in all our workflows

### ISSUE THREAD

**Issue by jboniface** [Expensify/Expensify.cash#3627]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

# Problem
We do not perform any caching of node modules in our GitHub Actions, and therefore each time we run `npm ci` it can take up to 5 minutes.

# Why is this important?
This is currently one of the biggest bottlenecks across all our Expensify.cash CI/CD. Setting up caching should speed up our testing and deployment substantially. I don't have data to back this, but I would guess that we could improve the average execution time of certain workflows by more than 50%.

# Solution
Use the [actions/cache](https://github.com/actions/cache) to [cache our dependencies and speed up our workflows](https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows).

[view this job on Upwork](https://www.upwork.com/jobs/~0179958076458d2f36)

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

**Comment by MelvinBot** [comment]
Triggered auto assignment to @puneetlath (`AutoAssignerTriage`), see https://stackoverflow.com/c/expensify/questions/4749 for more details.

**Comment by jboniface** [comment]
@puneetlath i already exported this to upwork, so you can skip the "external" label and just put "exported" on it after triage

**Comment by rushatgabhane** [comment]
## Proposal 
I'd add caching to all .yml files in .github/workflows which use npm ci.

This is an example of how node packages in test.yml would be cached.
https://github.com/Expensify/Expensify.cash/blob/5394fc8c55f860e98d926076cbac8221fea790b7/.github/workflows/test.yml#L19-L24
```
- name: Cache npm modules
  id: npmCache
  uses: actions/cache@v2
  with:
      path: ~/.npm
      key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      restore-keys: |
          ${{ runner.os }}-node-

- name: Install node packages
  uses: nick-invision/retry@7c68161adf97a48beb850a595b8784ec57a98cbb
  with:
      timeout_minutes: 10
      max_attempts: 5
      if: steps.npmCache.outputs.cache-hit != 'true'
      command: npm ci
```
